steps:
  # Executa o fluxo de trabalho de teste e captura a saída
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: ['-c', 'gcloud workflows run $_WORKFLOW_NAME-$BRANCH_NAME-$SHORT_SHA > /workspace/testoutput.log']

  # Checa a saída dos testes
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: ['gitops/test-$BRANCH_NAME.sh']

  # Etapa para implantar o fluxo de trabalho na produção
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['workflows', 'deploy', '$_WORKFLOW_NAME-$BRANCH_NAME', '--source', 'gitops/workflow.yaml']

options:
  logging: CLOUD_LOGGING_ONLY
