steps:
  # Passo 1: Construir a imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'southamerica-east1-docker.pkg.dev/llm-rag-maplink/assistente-juridico-obrigacao-de-fazer/assistente-juridico-obrigacao-de-fazer:$COMMIT_SHA',
        '.'
      ]

  # Passo 2: Enviar a imagem Docker para o Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'southamerica-east1-docker.pkg.dev/llm-rag-maplink/assistente-juridico-obrigacao-de-fazer/assistente-juridico-obrigacao-de-fazer:$COMMIT_SHA'
      ]

  # **Passo 3: Implantar no Cloud Run (com entrypoint corrigido)**
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run', 'deploy', 'assistente-juridico-obrigacao-de-fazer',
        '--image', 'southamerica-east1-docker.pkg.dev/llm-rag-maplink/assistente-juridico-obrigacao-de-fazer/assistente-juridico-obrigacao-de-fazer:$COMMIT_SHA',
        '--region', 'southamerica-east1',
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]

images:
  - 'southamerica-east1-docker.pkg.dev/llm-rag-maplink/assistente-juridico-obrigacao-de-fazer/assistente-juridico-obrigacao-de-fazer:$COMMIT_SHA'

options:
  substitution_option: 'ALLOW_LOOSE'
  logging: 'CLOUD_LOGGING_ONLY'
  machineType: 'E2_MEDIUM'

substitutions:
  _SERVICE_NAME: 'assistente-juridico-obrigacao-de-fazer'