# cloudbuild.yaml
steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'southamerica-east1-docker.pkg.dev/llm-rag-maplink/assistente-juridico/reclassificacao-processos-encerrados:v1',
        '.'
      ]

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'southamerica-east1-docker.pkg.dev/llm-rag-maplink/assistente-juridico/reclassificacao-processos-encerrados:v1'
      ]

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run', 'deploy', 'reclassificacao-processos-encerrados',
        '--image', 'southamerica-east1-docker.pkg.dev/llm-rag-maplink/assistente-juridico/reclassificacao-processos-encerrados:v1',
        '--region', 'southamerica-east1',
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]

images:
  - 'southamerica-east1-docker.pkg.dev/llm-rag-maplink/assistente-juridico/reclassificacao-processos-encerrados:v1'

options:
  substitution_option: 'ALLOW_LOOSE'
  logging: 'CLOUD_LOGGING_ONLY'
  machineType: 'E2_MEDIUM'

substitutions:
  _SERVICE_NAME: 'reclassificacao-processos-encerrados'
